apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: billing-handler-10157
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/billing-handler-10157
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
